#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes.
#
version: "3.3"

services:
    prometheus:
        image: prom/prometheus
        entrypoint: /bin/prometheus
        command: --web.listen-address=0.0.0.0:9090 --config.file=/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
        ports:
            - 9090:9090
        volumes:
            - ./prometheus:/prometheus
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/provisioning/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml

networks:
  default:
    external:
      name: lighthouse-docker_default
